version: '3.9'

services:

  db:
    image: postgres
    restart: always
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=notes
      - POSTGRES_USER=hiring
      - POSTGRES_PASSWORD=hiring
      - POSTGRES_HOST_AUTH_METHOD=trust

  api:
    build: ./api
    restart: always
    expose:
      - '8000'
    ports:
      - '8000:8000'
    depends_on:
      - db
    command: sh -c "/wait && ./scripts/run.sh"
    environment:
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=5

  web:
    restart: always
    build:
      context: "./fe/"
      dockerfile: Dockerfile
    expose:
      - '3000'
    ports:
      - '3000:3000'
    depends_on:
      - db
      - api
    command: npm run start
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
      - NEXT_PUBLIC_API_BASE_VERSION=v1
